### PR TITLE
Forgot scopes in next step. Plus added token types.

### PR DESCRIPTION
**Pull request by abjorck**
Got it working now, though!

### CODE REVIEW

**Comment by Clancey** [comment]
which api is this fixing? Not everyone does OAuth the same, You can override this at the API level. I am worried this may break the others.

**Comment by abjorck** [comment]
yeah the tokens should probably be moved out. but the scope couldn't hurt? 

you're saying i should override the function or is the parameters settable from the api level?
using it with azure b2c ad.

**Comment by abjorck** [comment]
It may very well break for 'normal' AD. It seems MS has several ways of
doing most everything but you need to do the right one in the right
contexts. :)

**Comment by abjorck** [comment]
yeah sorry haven't had time

**Comment by abjorck** [comment]
Verified now

**Pull request merged**
