### PR TITLE
OAuthApi udpated

### PR DESCRIPTION
**Pull request by wsdt**
Dropbox, Github, LinkedIn work now. 
- Removed now redundant instagram override

### CODE REVIEW

**Comment by Clancey** [comment]
Thanks for the pull request. I am a little hesitant to accept this pull request though. I believe the real issue is documentation on my part. I am 99% sure that you are having issues with redirects.  

I shy people away from the embedded browser due to security. It is way less secure and some providers like Google try and block you from using it.  Defaulting to it will break Google for login for sure.

Are you doing this to fix an iOS or Android project?  I am guessing Android since it is the hardest with redirects. You need to use a custom scheme and then deal with the [application.manifest](https://github.com/Clancey/simple_auth#android-manifest).

**Comment by wsdt** [comment]
The thing is: It does work with this change. 
Thus, I doubt that it has been implemented wrong.

**Comment by Clancey** [comment]
Sorry I didn't explain it very well. There are two different ways of presenting the web login page. One is by using the native secure login methods. (SFSsafari and CustomTabs). This is the default. It is harder to use but more secure and highly recommended if not required by most OAuth providers.  If your redirects are not correct/setup properly in your info.plist or application.manifest the redirects will not work.  The reason is the web page is outside your apps sandbox and needs a way to communicate back.

Your pull requests changes the default to use the second option. This option is a web view inside your app. It is a lot easier to setup, and some things like Instagram only work using the embedded browser since they do not allow you to register custom redirects schemes.  While this may make your code work it is overall not the direction I want to take this library. The embedded browser is not secure for end users. If you setup your project properly and register custom schemes for redirects as well as register them in the info.plist and application.manifest, this change is not needed.

While I am typically an advocate for making everything as simple as possible and removing as much developer friction as possible, I don't want to do that at the sacrifice of end users security.

**Comment by Clancey** [comment]
If you are having issues with getting this working without your changes, I would be happy to help.  I know these issues are caused due to my lack of documentation.  One thing we could do is maybe make it easier to opt into the embedded browser. But again I worry about end user security if it is used when it doesn't need to be.

**Pull request closed without merging**
