### PR TITLE
Removed some unneeded returns, fixed a spelling mistake

### PR DESCRIPTION
**Pull request by C-Alexander**
Solved #31 

Edit: removed the .vscode and .idea folders too

Very small change, just, it solved it for me locally and I figured I may as well do a PR before I make another change locally..

### CODE REVIEW

**Comment by C-Alexander** [comment]
For the record, this doesn't fix the whole thing. The code it generates has a few parameters in the wrong order and some other bugs. It needs some manual work once generated. I'll document them in issues sometime when I use it again, but I suspect the generator use case isn't that common right now, since the API is already quite simple to use anywhere and the generator just creates a very thin layer.

It just, for me, started generating code again after this.

**Comment by Clancey** [comment]
Thanks, for removing the .idea that was something I was going to recommend.  Also, what version of the SDK are you using. I have been trying to update the generator code to the latest and the dependencies have caused me a ton of issues. I think I have working dependencies now, but latest versions of analyzer break the generator code.  I am trying to get it all working locally again. 

Also, is it possible to attach the some of the APIs that will not generate for you? The ones I added inside the example all work on my mac. I wonder if things work differently on windows. I can test that later.

**Comment by Clancey** [comment]
I will merge this pull request as soon as I can things working on the latest versions and I can actually run the generator. Sorry for the delay.

**Comment by C-Alexander** [comment]
OK, so the problem was that a parameter was changed in simple_auth 1.0.6 to 1.0.7 for azure. Namely, redirecturl became required (which to be fair makes total sense). 

is there a reason we're not using Semver? It should be 2.0.0 according to Semver, as existing applications may break on upgrade, and the standard pubspec designation (^1.x.x) will automatically upgrade all users to any 1.x.x releases. 

-- for me it was extra confusing since I was  using the latest version of all packages, and the master of the generator since it was local. 

We also have an unnessescarily tough constraint in pubspec which probably isnt helping your build. Http is at 0.12 and up while flutter_test is at 0.11 right now, it doesn't need to be since the breaking changes shouldnt affect us (from a quick path search) So I've changed the specification for this package to 0.10 >= <0.13 which should be fine. 

I also did a minor fix to a constructor as it wasnt compatible with the latest versions of stuff, 

-- The test isn't working due some serious changes in Dart 2, fixing the symptoms is easy, but I think fixing it isn't worth it without also upgrading it to the latest versions, which removed some neccessary packages, so not bothering with it for now.

**Comment by Clancey** [comment]
Dependencies have been a nightmare for me. Writing this library is my first experience with flutter/dart. The I have been trying to get things to upgrade but the tooling is pretty lacking for helping with dependencies. Every time I update flutter it breaks all the dependencies.

Also as far as Semver, the project is still pretty new. Right now most the changes and versions have been fixing minor things to make the different providers work. Maybe it has just been ignorance on my part but I am pretty sure the user base is pretty low.  I most likely should not have even promoted it to 1.0 yet. But I think it's pretty close.

As I said, dependencies has been the worst part of building this library. I was unaware pub would auto upgrade. I will be more careful about that in the future. It is really getting to the state to where there shouldn't be anymore breaking changes. (I hope)

I am working on getting the test working again. I will hopefully get the dependencies figured out and the commit proper ranges for it.

**Comment by Clancey** [comment]
Alright, I think everything is now back to working.

**Comment by C-Alexander** [comment]
> Dependencies have been a nightmare for me. Writing this library is my first experience with flutter/dart. The I have been trying to get things to upgrade but the tooling is pretty lacking for helping with dependencies. Every time I update flutter it breaks all the dependencies.

You don't actually need tooling, but I do advice reading the page on pubspecs. It's really powerful and once you get the hang of it you'll have these problems way less often. 
https://www.dartlang.org/tools/pub/dependencies

Essentially whenever you do packages get, you get all the latest versions. IntelliJ likes doing it quite often, build servers... You can even do it while editing the code and hot reloading, it's very light and very powerful. The install manual recommends people to use ^, which upgrades to the highest non-breaking change, and people do this with great confidence itll be fine. 

To make it sane, it has a lot of tools to help you constrain versions. Right now you're basically letting it pick any it likes in a few of the involved libraries - this is dangerous and leads to scenarios where you end up in a "hell" of dependency changes, each conflicting with each other. Especially with flutter upgrades.

Instead, you want to basically say "I want at least the earliest version that works with my package, and no future versions with breaking changes". 


In early development, this means you want 0.33.1, 0.33.2, but never 0.34. That's where breaking changes go. 

Later on, this becomes 1.1, 1.2, but never 2.0. 

Right now almost everyone plays nice with this -- Analyzer seems sadly an exception (I don't think they expect anyone to depend on them -- they actually hid a lot of API's recently, it seems it's being automatically changed from one of Google's internal repositories.. And some breaking changes werent in the version log nor was the version upped... pretty bad). 

This package sadly is too :P 
 


Unlike some others 2 packages wont use 2 different versions of a binary under any circumstances, so Flutter is hugely dependant on everyone playing nice and picking as broad a selection of  potential version as possible, so Pub can select the highest version compatible with every package you have.

**Pull request merged**
